"""expenses added

Revision ID: 0a9fef768810
Revises: 7ab6e47bfdaf
Create Date: 2024-08-22 19:36:41.321431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a9fef768810'
down_revision = '7ab6e47bfdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('week_id', sa.CHAR(length=36), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['week.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('week', schema=None) as batch_op:
        batch_op.drop_column('expenses')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expenses', mysql.FLOAT(), nullable=True))

    op.drop_table('expense')
    # ### end Alembic commands ###
